export interface City {
  cityName: string;
  region: string;
  zipCode: string;
  country: string;
}

export const CITIES: City[] = [
  {
    cityName: "Paris",
    region: "Île-de-France",
    zipCode: "75000",
    country: "France",
  },
  {
    cityName: "Marseille",
    region: "Provence-Alpes-Côte d'Azur",
    zipCode: "13000",
    country: "France",
  },
  {
    cityName: "Lyon",
    region: "Auvergne-Rhône-Alpes",
    zipCode: "69000",
    country: "France",
  },
  {
    cityName: "Toulouse",
    region: "Occitanie",
    zipCode: "31000",
    country: "France",
  },
  {
    cityName: "Nice",
    region: "Provence-Alpes-Côte d'Azur",
    zipCode: "06000",
    country: "France",
  },
  {
    cityName: "Nantes",
    region: "Pays de la Loire",
    zipCode: "44000",
    country: "France",
  },
  {
    cityName: "Strasbourg",
    region: "Grand Est",
    zipCode: "67000",
    country: "France",
  },
  {
    cityName: "Montpellier",
    region: "Occitanie",
    zipCode: "34000",
    country: "France",
  },
  {
    cityName: "Bordeaux",
    region: "Nouvelle-Aquitaine",
    zipCode: "33000",
    country: "France",
  },
  {
    cityName: "Lille",
    region: "Hauts-de-France",
    zipCode: "59000",
    country: "France",
  },
  {
    cityName: "Rennes",
    region: "Bretagne",
    zipCode: "35000",
    country: "France",
  },
  {
    cityName: "Reims",
    region: "Grand Est",
    zipCode: "51100",
    country: "France",
  },
  {
    cityName: "Saint-Étienne",
    region: "Auvergne-Rhône-Alpes",
    zipCode: "42000",
    country: "France",
  },
  {
    cityName: "Toulon",
    region: "Provence-Alpes-Côte d'Azur",
    zipCode: "83000",
    country: "France",
  },
  {
    cityName: "Grenoble",
    region: "Auvergne-Rhône-Alpes",
    zipCode: "38000",
    country: "France",
  },
  {
    cityName: "Dijon",
    region: "Bourgogne-Franche-Comté",
    zipCode: "21000",
    country: "France",
  },
  {
    cityName: "Angers",
    region: "Pays de la Loire",
    zipCode: "49000",
    country: "France",
  },
  {
    cityName: "Nîmes",
    region: "Occitanie",
    zipCode: "30000",
    country: "France",
  },
  {
    cityName: "Villeurbanne",
    region: "Auvergne-Rhône-Alpes",
    zipCode: "69100",
    country: "France",
  },
  {
    cityName: "Clermont-Ferrand",
    region: "Auvergne-Rhône-Alpes",
    zipCode: "63000",
    country: "France",
  },
  {
    cityName: "La Rochelle",
    region: "Nouvelle-Aquitaine",
    zipCode: "17000",
    country: "France",
  },
  {
    cityName: "Perpignan",
    region: "Occitanie",
    zipCode: "66000",
    country: "France",
  },
  {
    cityName: "Amiens",
    region: "Hauts-de-France",
    zipCode: "80000",
    country: "France",
  },
  {
    cityName: "Antibes",
    region: "Provence-Alpes-Côte d'Azur",
    zipCode: "06600",
    country: "France",
  },
  {
    cityName: "Arras",
    region: "Hauts-de-France",
    zipCode: "62000",
    country: "France",
  },
  {
    cityName: "Béziers",
    region: "Occitanie",
    zipCode: "34500",
    country: "France",
  },
  {
    cityName: "Caen",
    region: "Normandie",
    zipCode: "14000",
    country: "France",
  },
  {
    cityName: "Cannes",
    region: "Provence-Alpes-Côte d'Azur",
    zipCode: "06400",
    country: "France",
  },
  {
    cityName: "Colmar",
    region: "Grand Est",
    zipCode: "68000",
    country: "France",
  },
  {
    cityName: "La Havre",
    region: "Normandie",
    zipCode: "76600",
    country: "France",
  },
  {
    cityName: "Avignon",
    region: "Provence-Alpes-Côte d'Azur",
    zipCode: "84000",
    country: "France",
  },
  {
    cityName: "Gap",
    region: "Provence-Alpes-Côte d'Azur",
    zipCode: "05000",
    country: "France",
  },
  {
    cityName: "Mime",
    region: "Île-de-France",
    zipCode: "93230",
    country: "France",
  },
  {
    cityName: "Beauvais",
    region: "Hauts-de-France",
    zipCode: "60000",
    country: "France",
  },
  {
    cityName: "Brest",
    region: "Bretagne",
    zipCode: "29200",
    country: "France",
  },
  {
    cityName: "Saint-Denis",
    region: "Île-de-France",
    zipCode: "93216",
    country: "France",
  },
  {
    cityName: "Châlons-en-Champagne",
    region: "Grand Est",
    zipCode: "51000",
    country: "France",
  },
  {
    cityName: "La Roche-sur-Yon",
    region: "Pays de la Loire",
    zipCode: "85000",
    country: "France",
  },
  {
    cityName: "Mulhouse",
    region: "Grand Est",
    zipCode: "68100",
    country: "France",
  },
  {
    cityName: "Chalon-sur-Saône",
    region: "Bourgogne-Franche-Comté",
    zipCode: "71100",
    country: "France",
  },
  {
    cityName: "Troyes",
    region: "Grand Est",
    zipCode: "10000",
    country: "France",
  },
  {
    cityName: "Carcassonne",
    region: "Occitanie",
    zipCode: "11000",
    country: "France",
  },
  {
    cityName: "Cesson-Sevigné",
    region: "Bretagne",
    zipCode: "35510",
    country: "France",
  },
  {
    cityName: "Ajaccio",
    region: "Corse",
    zipCode: "20000",
    country: "France",
  },
  {
    cityName: "Nanterre",
    region: "Île-de-France",
    zipCode: "92000",
    country: "France",
  },
  {
    cityName: "L'Haÿ-les-Roses",
    region: "Île-de-France",
    zipCode: "94800",
    country: "France",
  },
  {
    cityName: "Saint-Malo",
    region: "Bretagne",
    zipCode: "35400",
    country: "France",
  },
  {
    cityName: "Le Havre",
    region: "Normandie",
    zipCode: "76600",
    country: "France",
  },
  {
    cityName: "Évry-Courcouronnes",
    region: "Île-de-France",
    zipCode: "91000",
    country: "France",
  },
];
